version: "3.7"

services:
  gollum:
    image: gollumwiki/gollum:master
    #build: ./root
    restart: always
    ports:
      - "4567:4567/tcp"
    #environment:
        #- PAGE_FILE_DIR="/wiki"
        #- GOLLUM_BASE="/wiki"
    volumes:
      - ./config.rb:/etc/gollum/config.rb
      - ./wiki:/wiki
    command:
      - "--config=/etc/gollum/config.rb --page-file-dir=/wiki --mathjax"
